# oop - object oriented programming: Python, Java, C#, Rust, JavaScript ...
# functional - functional programming: Haskell, Scala, Clojure, Lisp, Prolog
# функційно-орієнтовані мови програмування: Haskell, Scala, Clojure, Lisp, Prolog, F#
